### ISSUE TITLE
pickupOnMine doesn't drop some items when inventory is full

### ISSUE THREAD

**Issue by WolfTammer730** [ForestOfLight/Canopy#1]
This is the problem Dim was having on Amelix, and I just encountered it too. It doesn't seem to happen for every block type, but things like stone, deepslate, and tuff won't drop
https://discord.com/channels/1261273546559066126/1265141466016252085/1265141466016252085

**Comment by ForestOfLight** [comment]
Does it only not drop items that are present in the inventory?

**Comment by WolfTammer730** [comment]
It appears so. did a quick test filling my inv with blackstone and mined netherrack (normally doesnt drop) and it dropped this time
