### ISSUE TITLE
Display | Fake player compatibility issue

### ISSUE THREAD

**Issue by Firebee45** [ForestOfLight/Canopy#2]
Ok so this is a issue with fake player and any info display pack and it happens to canopy too. When a player is spawned it sets a sphere around 0:0 based on where the player is (I have pictures attached) if you are outside of that sphere the display stops working. This is because the FP gets sent the display info too and it cases problems. This can be soled by adding a tag that people need to add for it to work that way it can’t be shown to the FP 
![B62EB71A-A415-4DA3-8B69-8AB9119DA937](https://github.com/user-attachments/assets/6111e8ce-1f6b-4432-b6b1-a12221f3a32a)
![30EBCE90-D631-4BDD-AA6E-389465D9A30B](https://github.com/user-attachments/assets/e60c6f95-99bc-46c6-a4c4-e01ae10d30df)
![462C16F8-0F3C-456D-A6B2-768528F5BD06](https://github.com/user-attachments/assets/6895593d-e161-4c33-b584-dfb0e9e5ffa2)
![4CBC4C04-FBAF-4D10-8A82-FD30FA189AA2](https://github.com/user-attachments/assets/1b32959a-d2c0-4126-bf2e-25fee9def45c)
![DE4DE6DE-47B9-439A-94FB-F7835E4CBEBF](https://github.com/user-attachments/assets/89008c0e-e147-498a-a568-447dae7688aa)

**Comment by ForestOfLight** [comment]
Fixed in v1.3.0.
