### ISSUE TITLE
Entities sometimes fails to clear when unloaded using ./health

### ISSUE THREAD

**Issue by WolfTammer730** [ForestOfLight/Canopy#5]
![Screenshot 2024-09-02 155853](https://github.com/user-attachments/assets/4029e8bb-44fc-4344-818e-8f43889e66ee)
This is on Amelix. There are four of us on the server all in the end dimension. We had been going in and out to the overworld for stuff, but this ss was taken when we were all in the end. The entities in the overworld are still tracked despite being in unloaded chunks. There was a ticking area at the AVC, however it has since been removed.

**Comment by ForestOfLight** [comment]
This is how Minecraft keeps track of entities. It is not a Canopy issue.

Canopy doesn't keep a running list of all the entities, it just gets the list from the game when you run the command.
